"""TwinGuide 病例配置的稳定入口。"""

from twin_guide.config._core import CaseConfig
from twin_guide.config.types import (
    DEFAULT_CONNECTOR_DIAMETER_MM,
    DEFAULT_GUIDE_ANCHOR_BACK_U_SIDE_RAY_ANGLE_DEGREES,
    DEFAULT_GUIDE_ANCHOR_U_SIDE_RAY_ANGLE_DEGREES,
    GeometryParameters,
    GuideAnchorLocation,
    GuideAnchorMode,
    GuideAnchorParameters,
    GuideAnchorSide,
    GuideComponentBridgeMode,
    GuideComponentBridgeParameters,
    GuideTerminalUExtensionMode,
    GuideTerminalUExtensionParameters,
    HandpieceAvoidanceParameters,
    InputMeshPaths,
    Jaw,
    PressBeamExtensionAnchorParameters,
    PressBeamGuideEndpointParameters,
    PressBeamMode,
    PressBeamParameters,
    PressBeamSleeveAnchorSelectionParameters,
    RenderParameters,
    SleeveGeometryMode,
    SleeveParameters,
    TerminalDistalCommonNodeParameters,
    ToothAnchorStation,
    ToothIdentificationInputs,
    WindowParameters,
)
from twin_guide.config.validation import case_occlusal_axis, require_production_review

__all__ = [
    "DEFAULT_CONNECTOR_DIAMETER_MM",
    "DEFAULT_GUIDE_ANCHOR_BACK_U_SIDE_RAY_ANGLE_DEGREES",
    "DEFAULT_GUIDE_ANCHOR_U_SIDE_RAY_ANGLE_DEGREES",
    "CaseConfig",
    "GeometryParameters",
    "GuideAnchorLocation",
    "GuideAnchorMode",
    "GuideAnchorParameters",
    "GuideAnchorSide",
    "GuideComponentBridgeMode",
    "GuideComponentBridgeParameters",
    "GuideTerminalUExtensionMode",
    "GuideTerminalUExtensionParameters",
    "HandpieceAvoidanceParameters",
    "InputMeshPaths",
    "Jaw",
    "PressBeamExtensionAnchorParameters",
    "PressBeamGuideEndpointParameters",
    "PressBeamMode",
    "PressBeamParameters",
    "PressBeamSleeveAnchorSelectionParameters",
    "RenderParameters",
    "SleeveGeometryMode",
    "SleeveParameters",
    "TerminalDistalCommonNodeParameters",
    "ToothAnchorStation",
    "ToothIdentificationInputs",
    "WindowParameters",
    "case_occlusal_axis",
    "require_production_review",
]
